version: '3.8'

services:
    database:
        image: postgres:latest
        container_name: operations_postgresql
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: operations
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    event-bus:
        image: wurstmeister/kafka:latest
        container_name: operations_kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_CREATE_TOPICS: 'events:2:2'
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: operations_zookeeper
        ports:
            - '2181:2181'
